server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/beidou?serverTimezone=GMT%2b8
    username: root
    password: HCRhcr020207



mybatis:
  #标注待解析的mapper的xml文件位置
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: D:/daima/xiaobaizuobishe2024/files/
#mvc:
#  pathmatch:
#    matching-strategy: ant_path_matcher

